name: postgrest_errors_package

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - .github/workflows/postgrest_errors.yaml
      - "packages/postgrest_errors/**"
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/postgrest_errors.yaml
      - "packages/postgrest_errors/**"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      working_directory: "packages/postgrest_errors"
