name: publish_postgrest_errors_dart_package

on:
  push:
    tags:
      - "postgrest_errors_dart_package-*"
  workflow_dispatch:

jobs:
  publish_package:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_pub_publish.yml@v1
    with:
      working_directory: packages/postgrest_errors
    secrets:
      pub_credentials: ${{ secrets.PUB_CREDENTIALS }}
